### ISSUE TITLE
About the pretrained models

### ISSUE THREAD

**Issue by 33KU** [ygjwd12345/GLANet#1]
Hi, can you provide me with trained models?

**Comment by ygjwd12345** [comment]
Sorry for the reply delay. I will release part of the checkpoint this weekend.

**Comment by ygjwd12345** [comment]
Hi, I upload some of my checkpoints on dropbox. Hope it would be useful for you.
Please check this [link](https://www.dropbox.com/sh/r8jwbonw5wtj44r/AADXIQ0p70GFVuTxq7b-VIaca?dl=0)
